version: '3.8'

services:
  mpi:
    build: .
    environment:
      - OMPI_ALLOW_RUN_AS_ROOT=1
      - OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
    command: mpirun -n 4 python3 primos_mpi.py
    networks:
      - mpi-net

networks:
  mpi-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.25.0.0/16"
